/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fes.aragon.swing.clases;

import fes.aragon.except.IndiceFueraDeRango;
import fes.aragon.problema2.utilerias.dinamicas.listadoble.ListaDoble;
import fes.aragon.problema2.utilerias.dinamicas.listasimple.ListaSimple;
import javax.swing.JOptionPane;

/**
 *
 * @author omar1
 */
public class Menu extends javax.swing.JDialog {

	ListaSimple<ListaDoble<Object>> lista = null;

	/**
	 * Creates new form InicioPrograma
	 */
	public Menu(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		this.setResizable(false);
		this.setLocationRelativeTo(this);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		btnLlenar = new javax.swing.JButton();
		btnImprimir = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtTexto = new javax.swing.JTextArea();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		btnLlenar.setText("Llenar lista (enteros)");
		btnLlenar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnLlenarActionPerformed(evt);
			}
		});

		btnImprimir.setText("Imprimir Listas");
		btnImprimir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnImprimirActionPerformed(evt);
			}
		});

		txtTexto.setEditable(false);
		txtTexto.setColumns(20);
		txtTexto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
		txtTexto.setRows(5);
		jScrollPane1.setViewportView(txtTexto);

		jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
		jLabel1.setText("Lista:");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(30, 30, 30)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(btnLlenar, javax.swing.GroupLayout.PREFERRED_SIZE, 154,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(188, 188, 188).addComponent(btnImprimir,
												javax.swing.GroupLayout.PREFERRED_SIZE, 143,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(30, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(8, Short.MAX_VALUE).addComponent(jLabel1).addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(btnImprimir).addComponent(btnLlenar, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(18, 18, 18)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnImprimirActionPerformed
		try {
			this.txtTexto.setText(this.lista.imprimir());
		} catch (IndiceFueraDeRango ex) {
			ex.printStackTrace();
		}
	}// GEN-LAST:event_btnImprimirActionPerformed

	private void btnLlenarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLlenarActionPerformed
		ListaSimple<ListaDoble<Object>> lista = new ListaSimple<>();
		this.lista = lista;
		// Se puede mejorar preguntando el numero de listas y el numero de elementos de
		// cada una
		// Pedir el tipo de dato
		Integer filas = Integer.parseInt(JOptionPane.showInputDialog(null, "Cuantas filas desea?"));
		Integer columnas = Integer.parseInt(JOptionPane.showInputDialog(null, "Cuantas columnas desea"));
		lista.rellenar(filas, columnas);
	}// GEN-LAST:event_btnLlenarActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnImprimir;
	private javax.swing.JButton btnLlenar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea txtTexto;
	// End of variables declaration//GEN-END:variables
}
